apiVersion: v1
kind: Pod
metadata: 
  name: object-detection-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            # - NVIDIA-GeForce-RTX-3090
            - NVIDIA-A100-SXM4-80GB
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/yg5d6/yolov8:torch2.3
    command: ["/bin/sh", "-c"]
    args:
    - pip install gdown;
      pip install ultralytics;
      mkdir /workspace/data;
      cd /workspace/data;
      gdown https://drive.google.com/uc?id=1xOo8C3QgjOz9Hj6hBqHmnoiSRtwO-o4C;
      gdown https://drive.google.com/uc?id=1pwjI64dLmCDtTW3QbKP4gt7yvlDWkuAG;
      unzip images-20241002T033820Z-001.zip;
      unzip labels-20241002T032645Z-001.zip;
      wandb login a9d4d981ca28ba6b6729e2a29464674ca243b891;
      sleep infinity;
    resources:
      limits:
        memory: "32G"
        cpu: "16"
        # nvidia.com/gpu: "1"
        nvidia.com/a100: "1"
      requests:
        memory: "32G"
        cpu: "16"
        # nvidia.com/gpu: "1"
        nvidia.com/a100: "1"
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm