apiVersion: v1
kind: Pod
metadata: 
  name: test-pod-gpus
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            # - NVIDIA-A100-SXM4-80GB
            # - NVIDIA-RTX-A6000
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-A10
            - NVIDIA-RTX-A5000
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: gpu-container
    image: ultralytics/ultralytics
    command: ["/bin/sh", "-c"]
    args:
    - pip install gdown;
      sleep infinity;
    resources:
      limits:
        memory: "16G"
        cpu: "8"
        # nvidia.com/a100: "1"
        # nvidia.com/rtxa6000: "1"
        nvidia.com/gpu: "1"
      requests:
        memory: "16G"
        cpu: "8"
        # nvidia.com/a100: "1"
        # nvidia.com/rtxa6000: "1"
        nvidia.com/gpu: "1"
    volumeMounts:
    - name: dshm
      mountPath: /dev/shm
